### ISSUE TITLE
Fork of github.com/aszmyd/grunt-hockeyapp?

### ISSUE THREAD

**Issue by janpio** [werk85/grunt-hockeyapp-upload#2]
Is this a for of https://github.com/aszmyd/grunt-hockeyapp? 
What got changed?

**Comment by mlegenhausen** [comment]
This is not a fork it is a new implementation cause we can't get the other plugin to work correctly.

**Comment by janpio** [comment]
OK, see that now. The similar README threw me off. 

Good work!
